name: rx_state
description: "A lightweight reactive state management built on rxdart."
version: 0.0.1
homepage: https://github.com/riad804/rx_state
repository: https://github.com/riad804/rx_state
issue_tracker: https://github.com/riad804/rx_state/issues

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true